// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20240815024346_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 123,
                            CreationDate = new DateTime(2024, 8, 15, 2, 43, 45, 916, DateTimeKind.Utc).AddTicks(3921),
                            Name = "test1",
                            Picture = "string",
                            Price = 123m
                        },
                        new
                        {
                            Id = 2,
                            Code = 123,
                            CreationDate = new DateTime(2024, 8, 15, 2, 43, 45, 916, DateTimeKind.Utc).AddTicks(3924),
                            Name = "test2",
                            Picture = "string",
                            Price = 123m
                        },
                        new
                        {
                            Id = 3,
                            Code = 123,
                            CreationDate = new DateTime(2024, 8, 15, 2, 43, 45, 916, DateTimeKind.Utc).AddTicks(3925),
                            Name = "test3",
                            Picture = "string",
                            Price = 123m
                        },
                        new
                        {
                            Id = 4,
                            Code = 123,
                            CreationDate = new DateTime(2024, 8, 15, 2, 43, 45, 916, DateTimeKind.Utc).AddTicks(3926),
                            Name = "test4",
                            Picture = "string",
                            Price = 123m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
